### ISSUE TITLE
Error when using PostgreSql

### ISSUE THREAD

**Issue by nozreh** [MatissJanis/oc-mail#27] opened 2017-06-06 06:37 UTC
Hi,
There was an Error when enabling the plugins, I'm using PostgreSql database.
https://drive.google.com/file/d/0B-adqvQw9iQ4U1FvSEdnTnQzak0/view?usp=sharing

**Comment by MatissJanis** [comment] 2017-06-06 06:40
Duplicate of #13

**Closed as completed by MatissJanis** 2017-06-06 06:40 UTC
